[project]
name = "common_toml"
version = "0.1.0"
dependencies = [
    # part1
    "neo4j~=5.28",
    "python-dotenv>=1.2.1",

    # part2 (csv2kg)
    "pandas~=3.0",
    "ipykernel>=6.29.0",

    # part3 (pdf2kg)
    "openai>=2.0.0",
    "langchain-text-splitters>=1.1.0",
    "PyMuPDF>=1.25.0",
    "docling>=2.0.0",
    "docling-hierarchical-pdf>=0.1.0",
]